### ISSUE TITLE
Reorganize Parcel/Transaction Error

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1053]
Currently, the criteria for classifying [ParcelError](https://github.com/CodeChain-io/codechain/blob/master/types/src/transaction/parcel_error.rs) and [TransactionError](https://github.com/CodeChain-io/codechain/blob/master/types/src/transaction/error.rs) are ambiguous.
Let it be clear by separating them into RuntimeError, SyntaxError and HistoryError.

* TransactionError
    - InvalidAssetQuantity : RuntimeError
    - AssetNotFound : RuntimeError
    - AssetSchemeDuplicated : RuntimeError
    - InvalidAssetType : SyntaxError
    - ScriptHashMismatch : RuntimeError
    - InvalidScript : SyntaxError
    - FailedToUnlock : RuntimeError
    - InconsistentTransactionInOut : SyntaxError
    - DuplicatedPreviousOutput : SyntaxError
    - InsufficientPermission : RuntimeError
    - EmptyShardOwners : SyntaxError
    - NotApproved : RuntimeError
    - ZeroZmount : SyntaxError
    - TooManyOutputs : SyntaxError
    - EmptyInput : SyntaxError
    - CannotBurnCentralizedAsset : RuntimeError
    - CannotComposeCentralizedAsset : RuntimeError
    - InvalidDecomposedInput : RuntimeError
    - InvalidComposedOutput : RuntimeError
    - InvalidDecomposedOutput : RuntimeError
    - EmptyOutput : SyntaxError
    - Timelocked : HistoryError
    - InvalidOriginOutputs : SyntaxError
    - InvalidOrderInOutIndices : SyntaxError
    - InconsistentTransactionInOutWithOrders : SyntaxError
    - InvalidOrderAssetTypes : SyntaxError
    - InvalidOrderAssetQuantities : SyntaxError
    - InvalidOrderLockScriptHash :SyntaxError
    - InvalidOrderParameters : SyntaxError
    - OrderRecipientsAreSame : SyntaxError
    - OrderExpired : HistoryError
* ParcelError
    - TransactionAlreadyImported : HistoryError
    - Old : HistoryError
    - TooCheapToReplace : HistoryError
    - InvalidNetworkId : SyntaxError
    - MetadataTooBig : SyntaxError
    - LimitReached : HistoryError
    - InsufficientFee : SyntaxError
    - InsufficientBalance : RuntimeError
    - InvalidSeq : HistoryError
    - InvalidShardId : RuntimeError
    - ZeroQuantity : SyntaxError
    - InvalidSignature : SyntaxError
    - InconsistentShardOutcomes : RuntimeError
    - TransactionIsTooBig : SyntaxError
    - RegularKeyAlreadyInUse : RuntimeError
    - RegularKeyAlreadyInUseAsPlatformAccount : RuntimeError
    - InvalidTransferDestination : RuntimeError
    - InvalidTransaction : removed
    - InsufficientPermission : RuntimeError
    - NewOwnersMustContainSender : SyntaxError
    - TextVerificationFail : SyntaxError
    - TextNotExist : SyntaxError
    - TextContentTooBig : SyntaxError

**Comment by sgkim126** [comment]
I'm not sure but HistoryError can be named as MemPoolError.

**Comment by foriequal0** [comment]
Newly created:
 * InvalidAssetComposedOutputAmount : SyntaxEror
 * InvalidAssetDecomposedInputAmount : SyntaxError

**Comment by foriequal0** [comment]
Changed:
   InvalidAssetType : RuntimeError
   TextNotExist : RuntimeError
   TextVerificationFail : Split RuntimeError + SyntaxError
   NewOwnersMustContainSender : RuntimeError
