### ISSUE TITLE
Node should request pre-commit votes in Commit state in Tendermint engine

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1081]
Currently, a node request votes when the node's state is pre-vote or pre-commit.
But a node should request more votes in commit state.

Below link is the line which requests votes.
https://github.com/CodeChain-io/codechain/blob/3b52cdae403fb788f6628250811bb7c54163b82e/core/src/consensus/tendermint/mod.rs#L1628

**Comment by jhs7jhs** [comment]
Resolved by #1146
