### ISSUE TITLE
Reduce travis job trigger

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/codechain#1089]
1. No travis job in master
Since we only allow fast-forward merge, a job on master immediately after the merge would be exactly the same as a job on PR before the merge.

2. No travis job if the changes only touch documents.
 * Add [no ci] to commit message
   https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
 * Filter by Branch name (docs/*)
 * Inspect commit range
   https://reflectoring.io/skip-ci-build/

**Comment by sgkim126** [comment]
The second item looks good.
But is there a way to do the first one?
Does Travis know whether the commit is a merge commit or not?

**Comment by foriequal0** [comment]
There's a `type` condition variable that can be one of [`push`, `pull_request`, `api`, `cron`]
https://docs.travis-ci.com/user/conditions-v1
But I think it can't tell the difference between merge commit and push to master.
