### ISSUE TITLE
Sometimes the 8193'rd transaction is not mined

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1123]
When received more than 8192 transactions at the same time, 8192 transactions are mined in the same block, and other transactions would not be mined forever.

I found this error while running "tendermint-test-local."

**Comment by majecty** [comment]
I found that the source of 8192. Transaction propagation works only for first "maxBodySize" bytes in the mempool. If we translate the size to payment transaction's count, it is 8192.

**Comment by majecty** [comment]
Condition: 4 nodes are running in the Network, Sends 20000 transactions to nodes[0].

Current situation
1. nodes[0] receives 20000 transactions.
2. nodes[0] sent 8192 transactions to nodes[1], nodes[2] and nodes[3].
3. nodes[0] tries to create a block with 20000 transactions but it failed.
4. Another node creates a block with 8192 transactions.
5. nodes[0] consistently failed to create a block with 11808 transactions, other nodes creates empty blocks. And no transaction relays.

**Comment by jhs7jhs** [comment]
Currently `tendermint-test-local` uses the same scheme file from the tendermint E2E test.
The timeout of each step is 1000ms, and it is not enought to put 20000 txs in one block because putting one tx takes about 100~150 microseconds.
I'll make a new scheme file for it.
