### ISSUE TITLE
Report benign validators

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#121]
Report the proposer if no proposal was received.

We may punish the proposer if it keeps not proposing blocks.

**Comment by kseo** [comment]
Also see #85

**Comment by majecty** [comment]
@kseo What do you mean by "benign" validator? If the "benign" validator is the validators who does not sign on proposals, we concluded to reduce rewards of the validators.

**Comment by majecty** [comment]
A validator with less work receives less reward.
A validator that has never proposed a block go to jail.

Please refer the specification document for details.
