### ISSUE TITLE
Add `IncreaseAssetSupply`

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1221]
```rust
    IncreaseAssetSupply {
        asset_type: H160,
        shard_id: ShardId,
        output: Box<AssetMintOutput>,
        approvals: Vec<Signature>,
    },
```
Increase the total supply of the asset scheme, and create a new asset with given output.

**Comment by sgkim126** [comment]
@foriequal0 https://github.com/CodeChain-io/codechain/pull/1241 I added `SyntaxError::CannotChangeWcccAssetScheme`. Please use it for `IncreaseAssetSupply` also.

**Comment by foriequal0** [comment]
Next To-do: Add Action to SDK
