### ISSUE TITLE
Change chain_getBlock RPC to return the invoices

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#1287]
In the current interface,

when I want to know all the invoices of transactions in a block, I must repeat calling `chain_getInvoice` n times. It's inefficient.

**Comment by sgkim126** [comment]
I'm adding an invoice to `Transaction`. Currently, `Transaction` has optinal field `blockHash`, `blockNumber` and `transactionIndex` if it's on the chain. I'll add an invoice field like them.

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1302 fixed it.
