### ISSUE TITLE
Persistent transaction queue 

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#132]
Dump transaction queue on shutdown and then reload it on startup.

**Comment by sgkim126** [comment]
Typically, it's not necessary. But because CodeChain network has only one implementation, it's possible that all nodes die at the same time by a bug.
To prevent lost all pending transactions in this situation, we need a persistent transaction queue.

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1147 closes it.
