### ISSUE TITLE
CodeChain got panicked by wrong transaction.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1350]
While writing new test cases to check functionality of `Order`, I found a case that causes CodeChain to panic. This case occurs when the `spentQuantity` value of an order is larger than the `assetQuantityFrom` value of the order.
Here is the panic message in the log file.
`Thread 'http.worker0' panicked at 'attempt to subtract with overflow', types/src/transaction/order.rs:134`

**Comment by ScarletBlue** [comment]
While writing new test cases to check the functionality of Order, I found a case that causes CodeChain to panic. This case occurs when the spentQuantity value of an order is larger than the assetQuantityFrom value of the order.
Here is the panic message in the log file:
Thread 'http.worker0' panicked at 'attempt to subtract with overflow', types/src/transaction/order.rs:134

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1356 closed it
