### ISSUE TITLE
Snapshot synchronization

### ISSUE THREAD

**Issue by remagpie** [CodeChain-io/codechain#144]
https://github.com/CodeChain-io/codechain/blob/master/spec/Block-Synchronization-Extension.md

Depends on: https://github.com/CodeChain-io/codechain/issues/1884

Todo:
- [x] Generate snapshots periodically (10/31~)
  - [x] Compress/decompress chunk 
  - [x] Make a state into chunks
  - [x] Read & verify chunks and recover the state
  - [x] Make chunk snapshot and recover property test success  https://github.com/CodeChain-io/codechain/pull/1844 (~11/13)
  - [x] Add block event listener to snapshot periodically (~11/15) https://github.com/CodeChain-io/codechain/pull/1869
    - [x] for the tendermint (~11/19) https://github.com/CodeChain-io/codechain/pull/1874
  - [x] Snapshot configurations
    - [x] Set the expiration date https://github.com/CodeChain-io/codechain/pull/1875
- [x] Update the sync extension for snapshot sync
  - [x] Update network messages for snapshots (~11/14) https://github.com/CodeChain-io/codechain/pull/1843
  - [x] Switch to full sync after the snapshot sync is finished https://github.com/CodeChain-io/codechain/pull/1855 (~11/15) 
  - [x] Make snapshot header importable
    - [x] Make consensus extensions to work without parent header  (~11/27) (@Remagpie)
    - [x] Make blockchain work without history (~11/15) https://github.com/CodeChain-io/codechain/pull/1862
    - [x] Update sync extension to ignore total_score of status message (~11/19) https://github.com/CodeChain-io/codechain/pull/1864
  - [x] Fetch snapshot header from peers (~11/15) https://github.com/CodeChain-io/codechain/pull/1862
  - [x] Collect snapshots from peers (~11/22) https://github.com/CodeChain-io/codechain/pull/1872
- [x] RPC to query the snapshot information (~11/22) https://github.com/CodeChain-io/codechain/pull/1873
- [ ] Test functionallity on testnet (~12/1)

Good To Have: 
- [ ] Make the snapshot period configurable

**Comment by foriequal0** [comment]
Todo:
- [ ] Check snapshot is generated periodically.
- [ ] Synchronize transaction invoices, parcel invoices.
- [ ] Network extension for the snapshot sync.
- [ ] RPC to control the snapshot sync.

**Comment by Kais-DkM** [comment]
I thought snapshot is generated periodically in the current implementation.
Are there any more jobs to do for this?

**Comment by sgkim126** [comment]
@foriequal0 I moved TODO list on the issue description.
