### ISSUE TITLE
Upgrade rocksdb

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1441]
I suspect our old rocksdb causes #348. Let's upgrade the rockdbs and check if the problem disappears.

**Comment by majecty** [comment]
@sgkim126 What do you think about adding this issue in the Foundry?

**Comment by sgkim126** [comment]
I think we should close it. We cannot upgrade rocksdb for the specific version since we changed CodeChain to use https://crates.io/crates/kvdb-rocksdb. We should use the rocksdb that kvdb-rocksdb uses.
