### ISSUE TITLE
Script to check changed files doesn't work on OSX

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1449]
https://travis-ci.org/CodeChain-io/codechain/builds/516058552
This is a PR that changes only e2e tests.

The OS X Travis worker judged it only changes documents, but the Linux worker judged as expected.

osx: https://travis-ci.org/CodeChain-io/codechain/jobs/516058553#L152
linux: https://travis-ci.org/CodeChain-io/codechain/jobs/516058554

It seems that the extended regular expression works differently on OSX.

Please check it.
https://github.com/CodeChain-io/codechain/pull/1437/commits/925b953cad8d84108e148b422a17123ccdd4b595

**Comment by foriequal0** [comment]
Fixed: https://github.com/CodeChain-io/codechain/pull/1454
