### ISSUE TITLE
The spec file is not containing all possible transactions.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1450]
Now the spec file is not containing `IncreaseAssetSupply` and `ChangeAssetScheme`.
It should be added under the actions anchor point (https://github.com/CodeChain-io/codechain/blob/master/spec/JSON-RPC.md#actions).

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1456 closed it.
