### ISSUE TITLE
Heavy network traffic for block synchronization

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1460]
Let's find a way to reduce this traffic.

**Comment by majecty** [comment]
The tried changes below. It seems we don't need to do more in block synchronization.

[Do not request the next headers if the pivot score is not changed #1468](https://github.com/CodeChain-io/codechain/pull/1468)
[Update pivot to the best_header if the best_header is already imported #1478](https://github.com/CodeChain-io/codechain/pull/1478)
[Send header request to a random peer at every timeout #1480](https://github.com/CodeChain-io/codechain/pull/1480)
