### ISSUE TITLE
Add an RPC to remove pending transactions

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1482]

**Comment by junha1** [comment]
@sgkim126 What would be the parameters of the RPC? Time boundary? Or just delete all?

**Comment by sgkim126** [comment]
I think deleting all is enough for now.
How about you @majecty?

**Comment by majecty** [comment]
I agree with you. Let's remove all transactions in Mempool.

**Comment by junha1** [comment]
I'll work on writing test code first.
