### ISSUE TITLE
Add an RPC to remove the Tendermint's backup data

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1483]

**Comment by sgkim126** [comment]
IMO it should be added to the devel category.

**Comment by majecty** [comment]
It was necessary to modify and debug the Tendermint code frequently. At that time, when there was a problem, the view between the codechain nodes was so high that it was difficult to reach a consensus again.

Now, even when the view differs a lot, CodeChain follows other nodes fast.
