### ISSUE TITLE
Early stage of sync is slow with many 'AlreadyQueued' log

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/codechain#1511]
```bash
#!/usr/bin/env bash
set -e

cargo build --release

export ENABLE_DELEGATIONS=true
export ENABLE_ORDER=true
export RUST_LOG=info,mio=warn,tokio=warn,hyper=warn,rpc=info

./target/release/codechain -c corgi --jsonrpc-port 8080 --port 3485 --enable-devel-api --no-miner --no-discovery --bootstrap-addresses $BOOTSTRAP
```

Sync on corgi is slow (less than few dozens per sec) on its early stage (less than 10000 blocks).
After that suspicious logs such as 'AlreadyQueued' is reduced and synchronization speed become more faster (few hundreds per sec).

It is not an accurate report. 
We should investigate more on this.
sgkim suggested `--no-tx-relay` would help to speed up, but it seems not.

**Comment by foriequal0** [comment]
https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide
Inspect rocksdb stats.

**Comment by sgkim126** [comment]
@foriequal0 Would you test after increasing [max_blocks_to_import](https://github.com/CodeChain-io/codechain/blob/00faf71b4e298010d5fdf60b0ebcdc1efdb0a0d2/core/src/client/importer.rs#L93)?

**Comment by foriequal0** [comment]
It got a few times faster after #1542. It can sync about 40 blocks per seconds at the early stage of sync. However, it still have more rooms to improve compared to the later stage of the sync.

**Comment by sgkim126** [comment]
Okay. Let's keep it open.

**Comment by HoOngEe** [comment]
perf report for
current implmentation:
![perf_before_separate](https://user-images.githubusercontent.com/20704471/58160982-66162780-7cba-11e9-8507-a3d44c63d41a.png)

after the separation `import lock` into `header_import_lock` and `body_import_lock`:
![perf_separated](https://user-images.githubusercontent.com/20704471/58161037-80500580-7cba-11e9-9871-28388a279de5.png)

**Comment by HoOngEe** [comment]
@Kais-DkM Is there any reason for using not headers[1..].iter() but headers.iter() ? in [this part](https://github.com/CodeChain-io/codechain/blob/82c62217df6be05ed3b995061d60149022cc9a18/sync/src/block/downloader/header.rs#L146)?
I think changing headers to headers[1..] would reduce overlaps.

**Comment by Kais-DkM** [comment]
No specific reason for that. But why do you want to change that?
I don't think importing the existing headers have a visible impact on performance.

**Comment by HoOngEe** [comment]
Yes, I made a mistake in measuring syncing time. As you mentioned, changing that part will not give us 
 any visible performance improvement.

**Comment by HoOngEe** [comment]
I considered evicting queued headers early from the downloaded cache. Though chances are very small, when any single node in the header queue is not imported until next request, codechain would be panicked on [this line](https://github.com/CodeChain-io/codechain/blob/83e8a4dba3910c4896f8e3f955d7996448fc640e/sync/src/block/downloader/header.rs#L127).

**Comment by HoOngEe** [comment]
The advantage of evicting pending headers mostly comes from saving rlp decoding time. 
Measured total time saving is about 14% and it corresponds to the following profiling results.

![without_pending_eviction](https://user-images.githubusercontent.com/20704471/58406657-0f875f80-80a5-11e9-82d9-60b52b868d88.png)
without pending eviction

![with_evicting_pending](https://user-images.githubusercontent.com/20704471/58409965-27161680-80ac-11e9-9e4d-8ec2978a5b0c.png)
with pending eviction

**Comment by majecty** [comment]
@foriequal0 @HoOngEe What is the current status of this issue?

**Comment by HoOngEe** [comment]
Too much generation of "AlreadyQueued" messages are now resolved with new data container `queued` in `DownloadCache`. We increased the sync speed slightly but not much.
And because we cannot fully take advantage of 8 threads, we decreased threads temporarily.
I think we can close this issue now.

**Comment by majecty** [comment]
OK. Thanks.
