### ISSUE TITLE
High memory usage while syncing

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1576]
During the block synchronization, codechain uses main memory over 8GB.
And the occupied memory was not cleared after the synchronization finished.

**Comment by HoOngEe** [comment]
Now I'm suspecting this comes from "not shrinking" the `Downloaded` like data implemented in `HeaderDownloader` and `BodyDownloader`. I checked that length of `queued` (see #1567, data of which was previously included in `downloaded`) reaches up to about 900,000.
That had not shrunk and will be alive continuously, I think the HashMap occupied huge amount of memory.

**Comment by HoOngEe** [comment]
`HashMap` has `shrink_to_fit` method, But I'm worrying about the reallocation overhead.
@foriequal0 showed me that the reallocation step occurs sparsely with doubling the previous size when inserting to `HashMap` but occurs densely when shrinking the `HashMap`.

**Comment by sgkim126** [comment]
Hi @HoOngEe,
Please call `shirink_to_fit` after removing items.
I don't think it becomes a burden to reallocate because `HashMap` allocates memory more than it needs when there is no capacity.
And please apply this change to `HashSet` and `Vec` in BodyDownloader.

**Comment by HoOngEe** [comment]
Here is the main reason of high memory. https://github.com/CodeChain-io/codechain/pull/1585#issuecomment-498098926
