### ISSUE TITLE
Reward curve does not match with spec.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1609]
![reward_curve](https://user-images.githubusercontent.com/20704471/58944350-9d0d3280-87bc-11e9-9b03-bd8e3e71d767.png)

I drew the two graphs: one following the spec (blue line), the other following the implementation(red line). They were not be completely folded up.  We should change one following the other.

**Comment by sgkim126** [comment]
@HoOngEe Would you fix it to follow the spec?
