### ISSUE TITLE
New RPC to get the signer of the transaction

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1652]
In the current implementation, it is hard to calculate the signer of the transaction returned by RPC.
The transaction has the signature and the hash, but it needs the hash of unsigned transaction to recover the signer.

At the first time, I considered that RPC returns the signer with the transaction, but it needs recovering the signature that is very CPU consuming task. So, calculating the signer for every transaction can waste the CPU of the node.

That's why I want to introduce a new RPC that returns the signer.

## chain_getTransactionSigner
Returns the signer of the given transaction hash.

It returns `null` if the transaction hash doesn't exist in the chain.

### Params
1. tx hash: `H256`

### Returns
`null` | `PlatformAddress`

### Request Example
```
  curl \
    -H 'Content-Type: application/json' \
    -d '{"jsonrpc": "2.0", "method": "chain_getTrnsactionSigner", "params": ["0xdb7c705d02e8961880783b4cb3dc051c41e551ade244bed5521901d8de190fc6"], "id": "who-is-authors"}' \
    localhost:8080
```

### Response Example
```
{
  "jsonrpc":"2.0",
  "result": "tccq94guhkrfndnehnca06dlkxcfuq0gdlamvw9ga4f",
  "id": "who-is-authors"
}
```

**Comment by majecty** [comment]
Is it just moving the heavy calculation from the SDK to the CodeChain instance?
I think that it is good to give the address since creating unsigned transaction's hash is hard.

**Comment by sgkim126** [comment]
@majecty. No, it's not merely moving the calculation from the SDK to the instance, because not all users need to use the SDK.
Currently, the user must use codechain-sdk to get the signer of the transaction or write complicated code to calculate the unsigned hash, but this RPC will make the user only needs the RPC.

**Comment by HoOngEe** [comment]
I understood you want to alleviate CPU load by restricting the signer calculation only to the existing transaction in the chain, right?

**Comment by sgkim126** [comment]
@HoOngEe NO. The code to calculate the signer from the transaction is complicated. I don't want that every user re-implements it or uses SDK just for this purpose.

**Comment by HoOngEe** [comment]
@sgkim126 Ok, I agree with your intention. The above question aimed at the "At first time~ " and "That's why" part.

**Comment by sgkim126** [comment]
@HoOngEe It's to restrict the caucluation but doesn't restrict the calculation for transactions in the chain. It restrict the signer calculation for the transaction that the user wants. In the most case, the signer of the transaction is not important and users will not care about it.
