### ISSUE TITLE
CodeChain works with less than minimum number of validators.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1675]
While I'm testing the beagle network, I found CodeChain is working only with 3 validators. Though the `minNumOfValidators` was set with 4, it was still proposing and finalizing blocks without a problem for about half a day.

```
curl \
    -H 'Content-Type: application/json' \
    -d '{"jsonrpc": "2.0", "method": "chain_getPossibleAuthors", "params": [26520], "id": "who-can-be-authors"}' \
    192.168.1.102:8664
{"jsonrpc":"2.0","result":["bccqygkycwleeu2upvx2na5y9g2jjenrf63tgarrpvh","bccq9rpp4vqd2tfk40yrpena5myt9dd2s8p2q64f2ph","bccqx7ezyfhxyjk7xdmycv8rjmjp542shzdaqdxfe2y"],"id":"who-can-be-authors"}
```

**Comment by HoOngEe** [comment]
[The comment](https://github.com/CodeChain-io/codechain/blob/0aff2579bbb65e04ccfc158f9f28745c7b1acb58/core/src/consensus/stake/action_data.rs#L310) imply the above reported behavior is intentional. When the number of validators becomes less than `min_num_of_validators`, we can handle the problem afterward.

**Comment by majecty** [comment]
OK, let's close the issue and leave it in the current implementation.
