### ISSUE TITLE
Use repoducible build for release binary

### ISSUE THREAD

**Issue by remagpie** [CodeChain-io/codechain#1732]
If the binary is built from the environment having a higher glibc version than the target machine, it returns an error similar to the following:
```
./codechain: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./codechain)
```

It's acceptible in the dev environment, but it should be avoided for the release builds.
We need to ensure that the release builds always have the same dependency.

**Comment by majecty** [comment]
We may use Docker to build a linux binary.

**Comment by majecty** [comment]
Gaia document has "Build Gaia Deterministically" section.
https://hub.cosmos.network/docs/reproducible-builds.html
