### ISSUE TITLE
Proposal for Redelegation

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1740]
Let me propose a new Custom Action: Redelegation.

Currently, to change the delegation, stakeholders should revoke the delegation and delegate again. If many stakeholders want to change their delegation at the same time, at one point, the total delegation amount can be drastically reduced. Then, candidates who have small delegations could be validators.

If we have a redelegation action, changing the delegation may not adversely affect the chain.

# How to add it
Add a new action to the Staking actions.

### Action

  * Format: `[6, prev_delegatee, next_delegatee, quantity]`
    - A `prev_delegatee` is an `AccountId`.
    - A `next_delegatee` is an `AccountId`.
    - `quantity` is a `u64` amount of CCS to redelegate to `next_delegatee` from `prev_delegatee`.

   Executing this action is the same as executing the revoke action and the delegate action. The `quantity` should be less than the delegated quantity of `prev_delegatee` from the sender.

### Example

```

    state = {
      stakeholders: [ "0x23..45", "0xAB..CD" ],
      balance: {
        "0x23..45": 500,
        "0xAB..CD": 900,
      },
      delegation: {
        "0xAB..CD": [ ["0x23..45", 100] ]
      }
    }
    
    > "0xAB..CD" sends staking action [ 6, "0x23..45", "0x67..89", 10 ]
    
    state = {
      stakeholders: [ "0x23..45", "0xAB..CD" ],
      balance: {
        "0x23..45": 500,
        "0xAB..CD": 900,
      },
      delegation: {
        "0xAB..CD": [ ["0x23..45", 90], ["0x67..89", 10] ]
      }
    }

```

**Comment by majecty** [comment]
@kseo @foriequal0 @HoOngEe Could you review this proposal?

**Comment by kseo** [comment]
@majecty LGTM

**Comment by foriequal0** [comment]
@majecty LGTM

**Comment by majecty** [comment]
Thanks, I'll implement it.
