### ISSUE TITLE
Network protocol stops for a long time

### ISSUE THREAD

**Issue by remagpie** [CodeChain-io/codechain#1752]
~One of our nodes had an issue that it couldn't receive any network data.~ The network session for other peers were running well.
It showed `Cannot read data from ..., ... bytes remain`, and the remaining number of bytes were higher than usual.

Heres the related log file.
[agent.log-2019082906.gz](https://github.com/CodeChain-io/codechain/files/3554233/agent.log-2019082906.gz)

**Comment by Remagpie** [comment]
This is the result of the the following command
```
zgrep "Cannot read" agent.log-2019082906.gz | awk ' { print $14 }' | sort | uniq -c
```
```
   1030 13.209.111.103:3485,
    998 13.209.206.83:39160,
   1395 13.209.252.252:55006,
   1705 15.164.52.243:3485,
    417 211.245.120.66:56906,
   2102 35.175.86.177:58702,
   2002 3.95.104.165:60558,
   5955 52.52.29.52:49128,
   1669 52.78.178.10:52348,
  16250 62.149.9.180:41474,
```

**Comment by Remagpie** [comment]
`211.245.120.66` was our office's IP, and all the other IPs except for the `62.149.9.180` were our machines in the cloud service.
Google search result says that `62.149.9.180` is from Kyiv, Ukraine.
