### ISSUE TITLE
Change VoteCollector::vote to return Result<(), DoubleVote<M>> rather than Option<DoubleVote<M>>

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/codechain#1766]
Rust can ensure `Result<T, E>` must be used while `Option<T>` doesn't. It'll prevent some classes of errors.

**Comment by HoOngEe** [comment]
Is this issue fully resolved with the pr#1800 or some other code is still remaining?

**Comment by foriequal0** [comment]
I'll close this.
