### ISSUE TITLE
Don't assume that valid proposal is always one in one round

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1773]
If a proposer double voted in one round, there could be two or more proposal blocks in the round.
One of the blocks could be finalized in the height.

**Comment by kseo** [comment]
@majecty what happens if there are two proposal blocks in one round?

**Comment by majecty** [comment]
I'm not sure what is the effect of it. I created this issue since the code depends on an invalid assumption.

**Comment by majecty** [comment]
If there are two proposal blocks in one round, the finalization time in a network disaster will be increased.
