### ISSUE TITLE
Use Rust 1.38.0

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#1804]
Rust 1.38.0 is available. https://blog.rust-lang.org/2019/09/26/Rust-1.38.0.html

**Comment by Remagpie** [comment]
Now rust 1.39.0 is available. https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html
How about using 1.39.0 instead?

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1850 uses 1.39.0
