### ISSUE TITLE
Does not respond to RPC requests after some error log

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1822]
Here is the log related to the error. After this log, CodeChain stoped responding to any RPC requests.
```
#555311344 2019-10-22 16:31:56.171982000 UTC http.worker00 ERROR jsonrpc_http_server  Error serving connection: Error { kind: Parse(Header) }
#555311344 2019-10-22 16:31:56.825757696 UTC http.worker00 WARN jsonrpc_http_server  Incoming streams error, closing sever: ()
```

**Comment by majecty** [comment]
I suspect that the new version of jsonrpc-http has a bug.

**Comment by majecty** [comment]
I'll test again with f71f74002a26caa50eafe997935a8f2c9a02cf34

**Comment by foriequal0** [comment]
They've fixed the bug: https://github.com/paritytech/jsonrpc/pull/515
Please update the packages to `14.0.3`
