### ISSUE TITLE
Move the Formatting Tool section in Wiki into the repository

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#1852]
I found that the Wiki page(https://github.com/CodeChain-io/codechain/wiki/Coding-Style#formatting-tool) is often being outdated.

We can move this document into the repository so that a developer, who tries to update the toolchain, can search and find it.

**Comment by kseo** [comment]
@joojis I think the wiki page is redundant because README.md already has sections on formatting and linting. What don't we get rid of the wiki?

**Comment by joojis** [comment]
@kseo I see. I removed the `Formatting Tool` and `Linting tool` sections from the page.
