### ISSUE TITLE
Make Tendermint implementation more snapshot friendly

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/codechain#1884]
We snapshot the state at the `term_end`. However, we can't simply boot a node with the Tendermint module from just a state snapshot because it looks up too many histories.

1. It reads the past state to retrieve `term_common_params`.

This behavior is introduced in this PR: https://github.com/CodeChain-io/codechain/pull/1715, and it was to solve this issue: https://github.com/CodeChain-io/codechain/issues/1710. 
It was made to read `last_term_finished_block_num` in the current state and to read `CommonParams` of the block whose block number is `last_term_finished_block_num`, which is not the best block, on every `on_close_block`.
This behavior won't be a problem if we snapshot right after the term closes.

2. We need all the headers in the previous term when we are closing a term.

Since votes for a block are sealed in the next block, we don't simply give rewards that are collected in the current term at the term close. (We can't foreknow which votes for the block are included at that time.)
We calculate additional rewards, penalties and distribute CCCs at the next term's close. This requires a node closing the term to read all the headers in the previous term.

Let's assume that we boot a node with snapshot `H102`, for example, and resume to full sync (downloads header, blocks and replaying the states).
One day, if the node tries to close term 5, it needs all headers in term 4 to calculate final rewards.
```
          closed                  closed
             v                        v HERE. PROBLEM!
~~~ term 4 ~~~|~~~~~~~ term 5 ~~~~~~~~~|
H100-H101-H102-H103-H104-H105-H106-H107-H108-H109...
             /\
            /  \ 
           /____\ 
        snapshot sync
```

We thought that it would be inevitable to download SOME headers that are preceding the snapshot header `H102`. After we found problem 2, it turns out that 'SOME' is a few hundred to cover all the headers of the previous term. Moreover, the exact number of 'SOME' cannot be retrieved with the `H102`'s state. We need `H101`'s state.

@kseo opposed the idea of 1. a more complex chunk format that covers multiple ranges of state 'FOREST' and 2. downloading two chunks `H102` and `H101`.

@Remagpie proposed that if rewards that will be given at `H107` is calculated at the opening of `H103`, it can be solved. We still distribute the reward at H107 to maintain the behavior in terms of CCC changes. It'll change how the state is calculated. Headers in term 4 is still needed to precalculate the rewards at `H103`. To make it unnecessary, @Remagpie also proposed that we should snapshot at `H103`.

However, if we take snapshot at `H103`, it triggers problem 1.

@Remagpie and @foriequal0 accepted @kseo 's argument: We should make the consensus independent from previous history/states and brainstormed some ideas. Here's the idea.

- [x] Introduce Era (https://github.com/CodeChain-io/codechain/pull/1893)
We'll introduce a monotonically increasing number to denote the consensus version called Era. It is increased when we fork. Other blockchain projects use block numbers to make a fork. However, block number based forks are sensitive to schedule postponing, and furthermore, it is not flexible for testing. Generic feature flags aren't suitable for the blockchain's feature set's nature. Features usually have strong serial dependencies. Thus, we use a monotonically increasing number.
- [x] Clone `CommonParams` at the term close in the state (https://github.com/CodeChain-io/codechain/pull/1895)
to solve the problem 1.
- [x] Precalculate the rewards and the penalties store in the state (https://github.com/CodeChain-io/codechain/pull/1900)
to solve the problem 2.
- [ ] ~Overloading `previous_last_term_finished_block_num` in `TermMetadata`~
is an alternative way to solve problem 2, but that requires the downloading of a few hundred headers.

**Comment by Remagpie** [comment]
PRs relate to this issue(https://github.com/CodeChain-io/codechain/pull/1893, https://github.com/CodeChain-io/codechain/pull/1895, https://github.com/CodeChain-io/codechain/pull/1900) are merged into the `era` branch.
It'll be merged to the master branch soon.
