### ISSUE TITLE
Add linux build to Travis

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#211]
Currently, Travis only builds Mac OS X binary. Add Linux build.

**Comment by sgkim126** [comment]
FYI, the linux build was removed because of the test failed that is not reproduced in the local environment.

**Comment by joojis** [comment]
It seems no problem for now. https://travis-ci.org/joojis/codechain/jobs/394063675

I'm going to make a PR for it. Any comment? @kseo @sgkim126

**Comment by kseo** [comment]
@joojis Let's do it.

**Comment by joojis** [comment]
Merged. https://github.com/CodeChain-io/codechain/pull/216
