### ISSUE TITLE
Repair broken snapshots

### ISSUE THREAD

**Issue by Kais-DkM** [CodeChain-io/codechain#219]
Snapshot can be boken in some situations.
Since snapshot sync protocol requires every snapshot to be valid, we need to repair every broken snapshot files before sending it out.
Current plan is to validate and repair all exisiting snapshot files once on startup.

**Comment by gurrpi** [comment]
Let me take care of this.

**Comment by gurrpi** [comment]
I caught the way merkle trie works. I'm planning to compare the snapshot file to keyvalueDB of state trie.

**Comment by sgkim126** [comment]
I moved it to https://github.com/CodeChain-io/codechain/issues/144
