### ISSUE TITLE
Add a RPC API to query coinbase address

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#228]
`chain_coinbase`: Returns the client coinbase address.

**Comment by kseo** [comment]
@joojis Would you add this API to the JSON RPC specification?

**Comment by joojis** [comment]
@kseo Sorry for the late reply. JSON-RPC spec is now available: https://github.com/CodeChain-io/codechain/blob/master/spec/JSON-RPC.md#chain_getcoinbase

**Comment by kseo** [comment]
@joojis The spec looks good to me.
