### ISSUE TITLE
Add option to specify base directory

### ISSUE THREAD

**Issue by Remagpie** [CodeChain-io/codechain#236]
Currently, config files are loaded from relative path from working directory.
We need be able to specify base directory to find them.

**Comment by kseo** [comment]
What about adding `--base-path` option?

**Comment by Kais-DkM** [comment]
What would be a default value in that case?

**Comment by kseo** [comment]
@Kais-DkM Current working directory is the default and `--base-path` overrides the default.

**Comment by sgkim126** [comment]
@HoOngEe Please close it if you have no issues.

**Comment by HoOngEe** [comment]
Resolved in the https://github.com/CodeChain-io/codechain/pull/1499
