### ISSUE TITLE
Miner does not mine transactions after reseal_min_period elapsed

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#239]
Miner does not mine transactions after waiting for `reseal_min_period` even though there are pending transactions.

**Comment by Kais-DkM** [comment]
This issue can be tested with following scripts:
main client:
```bash
cargo run -- --db-path db/db0 --port 3485 --jsonrpc-port 8080 --secret-key `printf "%064x" 1` -c solo
```
Sending parcel with SDK: https://gist.github.com/Kais-DkM/8864066978f1e49feb8f321b77448bcf

**Comment by kseo** [comment]
Change the default `reseal_min_period` to 0 in 5a7e35a9c6a9e53378dd950fdad7e169f0b829e8. This alleviates the issue a bit, but the problem still remains.
