### ISSUE TITLE
Add expiration time field to TransferAsset transactions

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#247]

**Comment by jhs7jhs** [comment]
@sgkim126 Is this still needed?

**Comment by sgkim126** [comment]
@jhs7jhs I think yes.
The current implementation only has a timelock for asset amount. It's different from expiration.

**Comment by sgkim126** [comment]
As I discussed with @jhs7jhs. We will add this field only to Transfer transaction, not all Transaction.
