### ISSUE TITLE
Rename getBlockNumber RPC method to getBestBlockNumber

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#252]

**Comment by kseo** [comment]
@joojis Why don't you add `getBestBlockInfo` and make it return both block number and hash?

**Comment by joojis** [comment]
I filed the new issue for the method that returns both number and hash: https://github.com/CodeChain-io/codechain/issues/290

Wiki updated: https://github.com/CodeChain-io/codechain/wiki/JSON-RPC#chain_getbestblocknumber
