### ISSUE TITLE
Prevent a node from connecting to itself

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#271]
Currently, the server continually tries to connect to itself.
Compare the address to connect with the local address can be an ad-hoc solution.
But there must be the other solution because comparing address cannot avoid the problem when one machine has multiple IP.

**Comment by kseo** [comment]
@sgkim126 The log message is quite annoying. Let's fix this issue ASAP.

**Comment by sgkim126** [comment]
#416, not the solution yet, will reduce the symptom.
