### ISSUE TITLE
Add errror handling code to run_account_command

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#287]
- Missing or invalid command line options are not handled
- `KeyStore` errors are not handled

**Comment by joojis** [comment]
Patch: 
https://github.com/CodeChain-io/codechain/commit/d35754750f40a8f38556b29476cccdf6a208962b
https://github.com/CodeChain-io/codechain/commit/29b5033635764569bb84cb654665c38864ecee70
