### ISSUE TITLE
Error in the sample code

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#317]
https://gist.githubusercontent.com/ScarletBlue/c2ce044b4a0fb38766b4e05cc7b4dcc6/raw/43862ea5f628b851a0b90410c0cdb6e4651445ec/sampleTransfer.js

```
console.log("Alice's lock script hash: ", bobLockScriptHash.value);
console.log("Alice's address: ", bobAddress.value);
```

`bobLockScriptHash` -> `aliceLockScriptHash`
`bobAddress` -> `aliceAddress`

**Comment by ScarletBlue** [comment]
코드가 크게 수정되면서 해결됐습니다.
