### ISSUE TITLE
Need a verifiable random number generator for probabilistic transaction

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#356]
# Verifiable random function

* Verifiable Random Functions 
https://people.csail.mit.edu/silvio/Selected%20Scientific%20Papers/Pseudo%20Randomness/Verifiable_Random_Functions.pdf

* Algorand: Scaling Byzantine Agreements for Cryptocurrencies
https://people.csail.mit.edu/nickolai/papers/gilad-algorand-eprint.pdf

# Commitment Scheme
* Tezos — a self-amending crypto-ledger White paper
https://tezos.com/static/papers/white_paper.pdf

**Comment by majecty** [comment]
I found this papers

verifiable random function
Verifiable Random Functions 
https://people.csail.mit.edu/silvio/Selected%20Scientific%20Papers/Pseudo%20Randomness/Verifiable_Random_Functions.pdf
Algorand: Scaling Byzantine Agreements for Cryptocurrencies
https://people.csail.mit.edu/nickolai/papers/gilad-algorand-eprint.pdf

commitment scheme
Tezos — a self-amending crypto-ledger White paper
https://tezos.com/static/papers/white_paper.pdf

**Comment by kseo** [comment]
Closing this issue because we excluded probabilistic transaction.
