### ISSUE TITLE
Change serialization of Bytes to string

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#384]
Currently, the type of `parameters` field in `Asset` and `AssetTransferOutput` is `Vec<Bytes>`.

The JSON serialization of `Bytes` is `Uint8Array` and it's hard to read(or debug) in the SDK environment.

![image](https://user-images.githubusercontent.com/9711879/42621721-7b8b5d14-85f9-11e8-9196-d8c0f1626934.png)

**Comment by sgkim126** [comment]
Change the type of `parameters` in https://github.com/CodeChain-io/codechain/blob/master/rpc/src/v1/types/asset_output.rs to `Vec<String>`
And make the type of parameters in SDK parse the string.

**Comment by sgkim126** [comment]
@HoOngEe You can convert Bytes to hex string with https://doc.rust-lang.org/std/fmt/#formatting-traits

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/blob/master/rpc/src/v1/types/unsigned_transaction.rs#L33
