### ISSUE TITLE
Rename account RPC APIs

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#434]
Our current naming scheme is quite redundant. Why don't we change the API names as follows?

account_createAccount -> account_create
account_createAccountFromSecret -> account_createFromSecret
account_removeAccount -> account_remove

**Comment by joojis** [comment]
@kseo I'm thinking of renaming `acount_createAccountFromSecret` to `account_importRaw` for consistency with CLI.

**Comment by joojis** [comment]
@kseo And also `account_getAccountList` -> `account_getList`

**Comment by kseo** [comment]
@joojis Sounds good.

**Comment by joojis** [comment]
Patch: https://github.com/CodeChain-io/codechain/pull/439

**Comment by joojis** [comment]
Closed.

SDK patch: https://github.com/CodeChain-io/codechain-sdk-js/pull/77
