### ISSUE TITLE
Remove build dependencies on spec files.

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#455]
Currently, codechain-core is rebuilt when the spec files(`core/res/*.json`) are modified.
The dependencies are not necessary since the spec files are read at runtime.

**Comment by sgkim126** [comment]
It seems that the spec files are loaded at compile time. It makes the single binary distribution possible.

**Comment by Kais-DkM** [comment]
@sgkim126 Could you provide specific line you're referring to?

**Comment by sgkim126** [comment]
@Kais-DkM https://github.com/CodeChain-io/codechain/blob/6a609186d1f3c927f6db97d977f576e21a0d3cf7/core/src/spec/spec.rs#L112-L120

**Comment by Kais-DkM** [comment]
Wow. I didn't know that `include_bytes` macro was run at compile time!
What an amazing feature!
