### ISSUE TITLE
Change unit test of stratum to use unused ports

### ISSUE THREAD

**Issue by Kais-DkM** [CodeChain-io/codechain#457]
Some unit tests in `stratum` crate opens network socket.
e.g. https://github.com/CodeChain-io/codechain/blob/420b63e97f275e043ff4367140547372ba2da219/stratum/src/lib.rs#L455
While it works and serves its own purpose, it's not a good practice to depend on external environment in unit test.
For example, if socket is already open by other application, the test will fail even if there's nothing wrong with its logic.
We should remove such tests, and find other way to test functionalities in those files.

**Comment by jhs7jhs** [comment]
@Kais-DkM I think it is inevitable by the structure of `Stratum`, but we can ensure the unit test works by checking socket addresses and using a socket address which is not used now.

**Comment by Kais-DkM** [comment]
@jhs7jhs Then what would be the correct operation when the port is already occupied?

**Comment by jhs7jhs** [comment]
@Kais-DkM Just find another port to open.

**Comment by Kais-DkM** [comment]
@jhs7jhs It seems we have to choose a range of ports for testing. Do you have any value in mind?

**Comment by Kais-DkM** [comment]
I agree with that. It seems good enough if there's no problem.
