### ISSUE TITLE
Don't accept same transaction twice

### ISSUE THREAD

**Issue by Kais-DkM** [CodeChain-io/codechain#458]
Currently, transaction with same hash is accepted even if same transaction already exists in blockchain.
It can cause serious problem since our current code assumes every transactions are executed only once.
For example, if same `AssetTransfer` transaction is issued twice, first can possibly succeed, but second one will always fail, overwriting previous result.

We have two options for this issue.
- Don't allow transaction such transactions, and drop it from mempool.
- Accept such transactions, but mark it as failed.

**Comment by kseo** [comment]
@Kais-DkM I think both options are not sufficient.

We must not accept a block that contains a transaction whose tx is is already in the chain.

**Comment by kseo** [comment]
Fixed in 33191e395d7d72369a38f74054cdffd61bea207e
