### ISSUE TITLE
Remove `Object` postfix from type names in JSON RPC specification

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#475]
The `Object` postfix is redundant.

`BlockObject` -> `Block`
`ParcelObject` -> `Parcel`

**Comment by joojis** [comment]
I'm on it.

**Comment by joojis** [comment]
Patch: https://github.com/CodeChain-io/codechain/commit/e9d56f6f2e15f5f2db3f122b07a154ca659e9638
