### ISSUE TITLE
Unreachable code reached

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#496]
====================

stack backtrace:
   0:        0x10ebf6014 - backtrace::backtrace::trace::h1460e79e73166f15
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:        0x10ebf114c - backtrace::capture::Backtrace::new_unresolved::h378d398c5a10302c
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:        0x10ebf109e - backtrace::capture::Backtrace::new::h87c95b9bf1dde611
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:        0x10ebefe4c - panic_hook::panic_hook::hcce522bafd8484e5
                        at util/panic_hook/src/lib.rs:53
   4:        0x10ebee588 - core::ops::function::Fn::call::h916a0f3d4df4bdfb
                        at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:73
   5:        0x110a37a24 - std::panicking::rust_panic_with_hook::h419f1703fae99798
                        at libstd/panicking.rs:467
   6:        0x110704de7 - std::panicking::begin_panic::hf6a09fbb0b315032
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:397
   7:        0x1102b51c2 - codechain_network::p2p::connection::Connection::reregister::h11d32c8394a3cfbf
                        at network/src/p2p/connection.rs:563
   8:        0x1102d63a1 - codechain_network::p2p::connections::Connections::reregister::h58dd685918859902
                        at network/src/p2p/connections.rs:180
   9:        0x110247f57 - codechain_network::p2p::handler::Manager::reregister_stream::hd1d600a5fb4730a4
                        at network/src/p2p/handler.rs:174
  10:        0x11024fa2d - _$LT$codechain_network..p2p..handler..Handler$u20$as$u20$codechain_io..IoHandler$LT$codechain_network..p2p..handler..Message$GT$$GT$::update_stream::hffd9f1d3c615f0ad
                        at network/src/p2p/handler.rs:545
  11:        0x1102c03af - _$LT$codechain_io..service..IoManager$LT$Message$GT$$u20$as$u20$mio..deprecated..handler..Handler$GT$::notify::h9c7217e3156ea37e
                        at /Users/kseo/codechain/util/io/src/service.rs:396
  12:        0x11023c9e5 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::notify::h77842a02893ec29f
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:345
  13:        0x11023ad95 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::io_process::h4515e6f63eff015d
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:329
  14:        0x11023e207 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::run_once::hada9cdcecfffb01f
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:303
  15:        0x11023c2c6 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::run::ha7a9aa59943270d3
                        at /Users/kseo/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:264
  16:        0x1102cb117 - _$LT$codechain_io..service..IoManager$LT$Message$GT$$GT$::start::hebe54403e21f76d6
                        at /Users/kseo/codechain/util/io/src/service.rs:230
  17:        0x1102cfd46 - _$LT$codechain_io..service..IoService$LT$Message$GT$$GT$::start::_$u7b$$u7b$closure$u7d$$u7d$::h5c14c730d167288e
                        at /Users/kseo/codechain/util/io/src/service.rs:545
  18:        0x11030b134 - std::sys_common::backtrace::__rust_begin_short_backtrace::h38f4142eda7656b1
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  19:        0x11021411b - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h25f485eecba358ad
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
  20:        0x1102d8b94 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::haa53f3296c74fc16
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:305
  21:        0x1102953d4 - std::panicking::try::do_call::h5c48d9f4260ff223
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  22:        0x110a4313e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  23:        0x110294949 - std::panicking::try::h36264f31192cb8ff
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
  24:        0x1102d8cc4 - std::panic::catch_unwind::h7feb211d29f28316
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
  25:        0x110213958 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h874f162d758be7a1
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
  26:        0x1102143d5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h8b5e0dc9afe28f59
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  27:        0x110a33a47 - std::sys_common::thread::start_thread::ha8ea81541cc9bee9
                        at libstd/sys_common/thread.rs:24
  28:        0x110a1f568 - std::sys::unix::thread::Thread::new::thread_start::hdd91fd3a2813e7e5
                        at libstd/sys/unix/thread.rs:90
  29:     0x7fff59115660 - _pthread_body
  30:     0x7fff5911550c - _pthread_start

Thread '<unnamed>' panicked at 'internal error: entered unreachable code', network/src/p2p/connection.rs:563

**Comment by sgkim126** [comment]
@majecty I think it is missed to handle the connection being disconnecting.
