### ISSUE TITLE
Check the "burns" field in the "AssetTransferTransaction" when queuing a parcel

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#517]
Solve this issue after the https://github.com/CodeChain-io/codechain-sdk-js/issues/103 is solved.

**Comment by kseo** [comment]
@majecty What do you mean by "checking the burns field"?

**Comment by majecty** [comment]
If we turn on the stratum, the crash is not shown.
However, if we turn off the stratum, it occurred.
I'm struggling with this problem.

**Comment by majecty** [comment]
@kseo I'll check whether is there any duplicated inputs among  `inputs` field and `burns` field.

**Comment by jhs7jhs** [comment]
@majecty When do we need to check it?

**Comment by majecty** [comment]
I want to check below things.
* Whether inputs and burns have some entries or not whose prev_out is the same.
* Whether some burn entries exist or not which have the same prev_out.
