### ISSUE TITLE
Use multi-stage builds to make lightweight docker image

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/codechain#541]
From Docker 17.05, Dockerfile can contains two or more ```FROM``` statements. Each ```FROM``` statements make new fresh stages, and can fetch build artifacts from previous named stages. We can make smaller images by removing build dependencies including only runtime dependencies in final stage.

docs: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by kseo** [comment]
Landed in f2909594787e128a97552f982e1092e9d18c8705
