### ISSUE TITLE
Filter meaningless errors before returning from RPC

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#549]
After #547, all parcel/transaction errors will be passed to JSON RPC. We need to filter meaningless errors.

**Comment by ScarletBlue** [comment]
@majecty return -> returning

**Comment by majecty** [comment]
@ScarletBlue I fixed it

**Comment by majecty** [comment]
This commit bcb5468960e6fe01fee6b3e3dbdac23ac36f1ba9 checks unreachable parcel errors.
All transaction errors could be returned by invoice.

I'll close this
