### ISSUE TITLE
`burns` field in AssetTransferTransaction is unintuitive

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#571]
In the mint-and-transfer example, I was trying to burn the asset, instead of transferring it.

```
const myFirstAsset = mintTx.getMintedAsset();
const transferTx = sdk.core.createAssetTransferTransaction()
    .addBurns(myFirstAsset);
```

I found that it causes an error because the P2PKH script doesn't contain BURN opcode.

**Comment by jhs7jhs** [comment]
I think the design is fixed now, but I also agree on this a little bit, because the owner of an asset should transfer at least once to burn the asset. I think this process is quite unnecessary.

**Comment by jhs7jhs** [comment]
Closing the issue for now.
