### ISSUE TITLE
account remove command should not require password confirmation

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#612]

**Comment by sgkim126** [comment]
I agree that the remove command should not require a password. But I think the remove command needs confirmation step something like typing the specific sentence to avoid accidentally removing an account.

**Comment by kseo** [comment]
@sgkim126 I will add a confirmation dialog.

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/881 fixes it.
