### ISSUE TITLE
Add integration test cases

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#639]
## Done
- Use account RPC
- Use net RPC
- Use chain RPC
- Mint assets
- Transfer assets
- Burn assets
- Mint and transfer an asset that has a registrar
- mempool size limit
- Send invalid parcels (own parcels)
- Send empty blocks
- Send a parcel using a regular key

## Added but has issues
- Block sync extension
   - [ ] timer issue (https://github.com/CodeChain-io/codechain/issues/662)
   - [x] wrong verification during a reorgnization (https://github.com/CodeChain-io/codechain/issues/736)
- Network Discovery (unstructured)
   - [ ] connection issues (https://github.com/CodeChain-io/codechain/issues/724)

## test-helper required
- [ ] Send invalid blocks and parcels through block-sync extension 
   - Invalid fields
   - Invalid size
   - ...

**Comment by jhs7jhs** [comment]
The skipping test cases will be discussed in #761

**Comment by joojis** [comment]
Moved out to https://github.com/CodeChain-io/codechain/issues/774 and https://github.com/CodeChain-io/codechain/issues/761
