### ISSUE TITLE
Read the config file at compile-time

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#665]
Currently, CodeChain reads the [config file](https://github.com/CodeChain-io/codechain/tree/master/codechain/config/presets) at run-time. Change it to read the config file at compile-time to make distribution easier.

**Comment by sgkim126** [comment]
I think it can be easily done with https://doc.rust-lang.org/std/macro.include_bytes.html

**Comment by kseo** [comment]
Landed in d7e0448006113c1bbae8fd236e0dcb71940b1274
