### ISSUE TITLE
Support tagging in a whitelist/blacklist

### ISSUE THREAD

**Issue by jhs7jhs** [CodeChain-io/codechain#668]
It is hard to distinguish each IPs in a whitelist/blacklist, so it should be good if tagging is supported in the whitelist/blacklist format.

**Comment by kseo** [comment]
@jhs7jhs Would you add an example of tagging?

**Comment by jhs7jhs** [comment]
Currently, there's no fixed format for it, but I think like this: (address, comment or tag)
```
127.0.0.1, localhost
A.B.C.D, node1
A.B.C.E, node2
...
```

**Comment by jhs7jhs** [comment]
@joojis This will change the JSON RPC format of `net_addToWhitelist`, `net_removeFromWhitelist`, `net_addToBlacklist`, `net_removeFromBlacklist`, `net_getWhitelist, and `net_getBlacklist`.
