### ISSUE TITLE
Timer is unstable on Travis

### ISSUE THREAD

**Issue by jhs7jhs** [CodeChain-io/codechain#759]
`timeout()` and `on_timeout()` is called late and irregularly on Travis (If setting the duration to 1 sec, the timeout method would be invoked after 3~10 sec), and it seems like it's because there are few CPU cores on the current Travis environment.
But it is not tested on low-core environment now, so adding the issue as `on Travis`.

**Comment by sgkim126** [comment]
Close it since we will implement a shared timer and removing mio timer.

**Comment by jhs7jhs** [comment]
I'll check this asap.
