### ISSUE TITLE
Use mocha instead of jasmine for test runner

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#779]
It seems that mocha is able to know whether the test failed in afterEach().

- https://github.com/mochajs/mocha/issues/797
- https://mochajs.org/api/runner.js.html

But I haven't found a spec or documentation for `currentTest` field. It needs to be confirmed.

**Comment by jhs7jhs** [comment]
@joojis It seems it's possible to do so. https://stackoverflow.com/questions/22031765/how-might-i-check-if-any-mocha-tests-failed-from-within-an-after-block

**Comment by jhs7jhs** [comment]
I've tried to find out the way to detect test failures in `afterEach` in Jest, but it's still not possible.
There's no way to escape from this issue. I'll try to migrate the integration test.
