### ISSUE TITLE
Use the appropriate words according to the use case when counting the asset, CCC

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain#799]
The CodeChain is currently using only a single "amount" word for use-cases that need to refer to supply, quantity, amount, and description.

Use the appropriate words according to the use case when counting the asset, CCC
```
Mint assets = supply
Transfer assets = quantity
Transfer CCC = quantity
```

**Comment by sgkim126** [comment]
@kseo It becomes weird because we have WCCC.
The unit of CCC is amount but the unit of WCCC will be quantity if we apply this change.

**Comment by sgkim126** [comment]
@kseo ping

**Comment by sgkim126** [comment]
Rename amount to quantity.
- [AssetOutPoint](https://github.com/CodeChain-io/codechain/blob/a2e4d9aee45023c5c12c929ce74d75cf700fa062/rpc/src/v1/types/asset_input.rs#L27), [AssetTransferOutput](https://github.com/CodeChain-io/codechain/blob/master/rpc/src/v1/types/asset_output.rs#L27), [Pay](https://github.com/CodeChain-io/codechain/blob/a2e4d9aee45023c5c12c929ce74d75cf700fa062/rpc/src/v1/types/action.rs#L90), [WrapCCC](https://github.com/CodeChain-io/codechain/blob/a2e4d9aee45023c5c12c929ce74d75cf700fa062/rpc/src/v1/types/action.rs#L108)
Rename amount to supply.
- [AssetMintOutput](https://github.com/CodeChain-io/codechain/blob/a2e4d9aee45023c5c12c929ce74d75cf700fa062/rpc/src/v1/types/asset_output.rs#L57)
