### ISSUE TITLE
Needs transaction types that convert CCC from/to an assset

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#831]
We need something similar to https://weth.io/

**Comment by sgkim126** [comment]
It depends on https://github.com/CodeChain-io/codechain/pull/845.

**Comment by jhs7jhs** [comment]
Now #852 is merged. Need to consider `chain_getAssetSchemeByType`, `chain_getAssetSchemeByHash` as the conversation on the PR.

**Comment by jhs7jhs** [comment]
Deploying docker-build on https://travis-ci.org/CodeChain-io/codechain/builds/453774165?utm_source=github_status&utm_medium=notification

**Comment by jhs7jhs** [comment]
Now implemented the SDK part. https://github.com/CodeChain-io/codechain-sdk-js/pull/250

**Comment by jhs7jhs** [comment]
Added integration test: #865
