### ISSUE TITLE
Needs additional RPCs 

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain#841]
I need some RPCs for implementing the applications like the wallet or explorer.
It is currently hardcoded according to each chain consensus.
- [ ] Mining rewards
- [ ] Address list on the genesis
- [ ] Finalization time

**Comment by sgkim126** [comment]
@xpdlf1004 I've added all RPCs. Would you review it?

**Comment by xpdlf1004** [comment]
@sgkim126 LGTM
