### ISSUE TITLE
The negotiation message implementation is different from spec

### ISSUE THREAD

**Issue by GNUp** [CodeChain-io/codechain#909]
The current negotiation message structure is below
```
#[derive(Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct Message {
    version: Version,
    seq: Seq,
    body: Body,
}

#[derive(Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Body {
    Request {
        extension_name: String,
        extension_versions: Vec<Version>,
    },
    Allowed(Version),
    Denied,
}
```
However, the spec document says
```
RequestBody := seq  . extension-name . extension-version
AllowedBody := seq
DeniedBody := seq . [ . version]*
```
https://github.com/CodeChain-io/codechain/blob/master/spec/P2P-Protocol.md

**Comment by GNUp** [comment]
@sgkim126 Would you check this, please?

**Comment by sgkim126** [comment]
@GNUp Thank you for checking. Let's fix the spec. Would you request the PR?

**Comment by GNUp** [comment]
@sgkim126 OKay. Also, I wonder more specific description about negotiation scheme. If the node who send negotiation request will register the version of extension which is used by target node that got the request, why there is a version field in negotiation request message? And what is the purpose of the negotiation denied message?

**Comment by sgkim126** [comment]
@GNUp If there are several versions and two nodes don't have the common version, the recipient sends Denied message. At my first design, the recipient sends its available version, but I removed it because initiator can do nothing with this information.

**Comment by GNUp** [comment]
@sgkim126 Okay, Thank you

**Comment by sgkim126** [comment]
Closed due to https://github.com/CodeChain-io/codechain/issues/1153
