### ISSUE TITLE
Exclude seal when calculating the block hash

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#91]
The same block can have different block hashes because the same block from different validators can have different set of COMMIT signatures.

**Comment by majecty** [comment]
This issue is related to the Tendermint consensus.

Validators who collect more than two-thirds of Precommits could create a finalized block in local. Since, each block has a different seal field, each block has a different hash.

**Comment by majecty** [comment]
I'll add an external_seal field to the header. When calculating a hash of a block, the external_seal field will be not included.

**Comment by majecty** [comment]
We concluded not to exclude seal when calculating the block hash.
To give a penalty to a sleeping node, we should share which validators have signed to a block. And the validator set should be fixed in a block.
