### ISSUE TITLE
Should not request same header repeatedly.

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#950]
If a node "A" received a "Status" message with a very high score from node "B", the "A" node request "Headers" to the node "B".
However, if the "B" did not give the header that has the high score, the node "A" infinitely sent "Headers" request to the node B.

The node "A" should wait for some time before sending a request or disconnect the node "B".

**Comment by sgkim126** [comment]
@majecty Is it fixed?

**Comment by majecty** [comment]
Yes fixed in the https://github.com/CodeChain-io/codechain/pull/1468
