### ISSUE TITLE
Tendermint gossip is not efficient

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#953]
Current implementation

*Proposal*

Not gossiped at all.

*Votes*

Resend the vote to all peers if the node received a new vote.
If prevote/precommit timeout occurred before collecting 2/3 of votes, the node sends all votes to all nodes.

*Inefficient point*

If a node does not need to send a vote message to a node which already knows the vote.

**Comment by sgkim126** [comment]
Move this issue to #953
