### ISSUE TITLE
Lock on nil in Tendermint

### ISSUE THREAD

**Issue by jhs7jhs** [CodeChain-io/codechain#976]
https://tendermint.com/docs/spec/consensus/consensus.html#state-machine-spec
It is possible to lock on `nil` when there's +2/3 prevotes for `nil`. But our code checks the +2/3 prevoted block is not `nil`.
https://github.com/CodeChain-io/codechain/blob/a9957f982b2ddf4f284eaad77546aacd4460d7c2/core/src/consensus/tendermint/mod.rs#L394

**Comment by majecty** [comment]
The docunment page says


> If the validator has a PoLC at (H,R) for a particular block B, it (re)locks (or changes lock to) and precommits B and sets LastLockRound = R. - Else, if the validator has a PoLC at (H,R) for \<nil\>, it unlocks and precommits \<nil\>. - Else, it keeps the lock unchanged and precommits \<nil\>.

The docunment page says unlock the lock when received 2/3 of nil messages. I thinks the sentence does not mean to lock on nil.

**Comment by jhs7jhs** [comment]
@majecty There's already a phrase: "a PoLC at (H,R) for <nil>". Also I put the code from Go Tendermint as reference.

**Comment by jhs7jhs** [comment]
I think I've misread the documentation. Closing.
