### ISSUE TITLE
Enhance Tendermint gossip

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#994]
We are now using push-based gossip. Since push-based gossip cannot get votes when it is needed, the node should keep future messages without verification, and that makes the code too complicated.

Changing the gossip to ignore future messages and receive only valid messages at current state makes the code simpler.

**Comment by majecty** [comment]
# How to be changed

Each node tracks the peers' status. And the node gives random messages which the peer didn't have.

# Messages to be added

```rust
struct StepState {
  height: Height,
  view: View,
  proposal: Option<Hash>
}
```

```rust
struct VoteReceived {
  index: i32,
  step: Step,
  height: Height,
  view: View
}
```

# Peer status

A node should maintain peers' state. The votes fields became empty when the step is changed. And the bit sequence is filled when a node sent a message to the node, or the node sent `VoteReceived` message.

```rust
struct PeerState {
  height: Height,
  view: View,
  proposal: Option<Hash>
  votes: Vec<byte> // bit sequence of prevotes / precommits
}
```

# Concern

A node could receive multiple proposal blocks. This could cause network overhead.

**Comment by sgkim126** [comment]
Why a node should track the peers?
These tries are usually fragile in a distributed network.

How about pull-based protocol.
The node just sends its status on an update, and peers respond according to its status.

**Comment by majecty** [comment]
Okay I'll change it pull based

**Comment by majecty** [comment]
@sgkim126 I changed it.

**Comment by sgkim126** [comment]
Should the node request to peers periodically?

**Comment by majecty** [comment]
If a node A received node B's status and node B has an unknown message, the node A requests the message.

If the B didn't send the response in timeout duration, A requests the message to B or other knwon peers.

**Comment by jhs7jhs** [comment]
@sgkim126 @majecty Is there any remaining job for this issue?

**Comment by sgkim126** [comment]
It seems that the second item is easy to implement.
But I worry that messages are not broadcasted to all nodes because some nodes found a cluster.

**Comment by majecty** [comment]
I'll add two separated issues.

**Comment by majecty** [comment]
I created #1936 and #1935
